# Specify lanauge we use is generic
language: generic

# Supper user permission to run doecker
sudo: required

# Tell Travis CI we need to use docker
services:
  - docker

# Setup commands before execute test command
before_install:
  - docker build -t chrischuang0421/docker-react-win -f Dockerfile.dev .

# Setup test commnads
# Add CI flag to run test only one
script:
  - docker run -e CI=true chrischuang0421/docker-react-win npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-win"
  env: "Dockerreactwin-env"
  bucket_name: "elasticbeanstalk-us-east-2-796215826286"
  bucket_path: "docker-react-win"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
